name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image to dockerhub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: hkseal/streamlit-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y kubectl
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
# kubectl set image deployment/<deployment-name> <container-name>=hkseal/streamlit-demo:latest

